.TH "Library Maintenance Functions" 3 "19 May 2008" "Embryo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Library Maintenance Functions \- Functions that start up and shutdown the Embryo library.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "EAPI int \fBembryo_init\fP (void)"
.br
.RI "\fIInitialises the Embryo library. \fP"
.ti -1c
.RI "EAPI int \fBembryo_shutdown\fP (void)"
.br
.RI "\fIShuts down the Embryo library. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions that start up and shutdown the Embryo library. 
.PP
.SH "Function Documentation"
.PP 
.SS "EAPI int embryo_init (void)"
.PP
Initialises the Embryo library. 
.PP
\fBReturns:\fP
.RS 4
The number of times the library has been initialised without being shut down. 
.RE
.PP

.SS "EAPI int embryo_shutdown (void)"
.PP
Shuts down the Embryo library. 
.PP
\fBReturns:\fP
.RS 4
The number of times the library has been initialised without being shutdown. 
.RE
.PP

