.TH "Byte Swapping Functions" 3 "25 Sep 2008" "Embryo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Byte Swapping Functions \- Functions that are used to ensure that integers passed to the virtual machine are in small endian format.  

.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "EAPI void \fBembryo_swap_16\fP (unsigned short *v)"
.br
.RI "\fIEnsures that the given unsigned short integer is in the small endian format. \fP"
.ti -1c
.RI "EAPI void \fBembryo_swap_32\fP (unsigned int *v)"
.br
.RI "\fIEnsures that the given unsigned integer is in the small endian format. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions that are used to ensure that integers passed to the virtual machine are in small endian format. 
.PP
These functions are used to ensure that the virtual machine operates correctly on big endian machines. 
.SH "Function Documentation"
.PP 
.SS "EAPI void embryo_swap_16 (unsigned short * v)"
.PP
Ensures that the given unsigned short integer is in the small endian format. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP Pointer to the given integer. 
.RE
.PP

.SS "EAPI void embryo_swap_32 (unsigned int * v)"
.PP
Ensures that the given unsigned integer is in the small endian format. 
.PP
\fBParameters:\fP
.RS 4
\fIv\fP Pointer to the given integer. 
.RE
.PP

.PP
Referenced by embryo_program_load().
