.TH "todo" 3 "25 Sep 2008" "Embryo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBpage \fBEmbryo Library Documentation\fP \fP" 1c
Clean up compiler code. 
.PP
.PP
 
.IP "\fBpage \fBEmbryo Library Documentation\fP \fP" 1c
Proper overview of the operation of the interpreter, that is how the heap, stack, virtual machines, etc fit together. 
.PP
.PP
 
.IP "\fBPage \fBAvailable Calls\fP \fP" 1c
Finish this section.
.PP
.PP

