Embryo: Program Creation and Destruction Functions
Home
News
About
Download
Main Page Modules API Reference Related Pages
Support
Contribute
Contact
Tracker
Program Creation and Destruction Functions
Functions that set up programs, and destroy them.
Functions
EAPI Embryo_Program * embryo_program_new (void *data, int size)
Creates a new Embryo program, with bytecode data that can be freed.
EAPI Embryo_Program * embryo_program_const_new (void *data, int size)
Creates a new Embryo program, with bytecode data that cannot be freed.
EAPI Embryo_Program * embryo_program_load (char *file)
Creates a new Embryo program based on the bytecode data stored in the given file.
EAPI void embryo_program_free (Embryo_Program *ep)
Frees the given Embryo program.
Detailed Description
Functions that set up programs, and destroy them.
Function Documentation
EAPI Embryo_Program* embryo_program_const_new (void * data, int size)
Creates a new Embryo program, with bytecode data that cannot be freed.
Parameters:
data Pointer to the bytecode of the program.
size Number of bytes of bytecode.
Returns:
A new Embryo program.
EAPI void embryo_program_free (Embryo_Program * ep)
Frees the given Embryo program.
Parameters:
ep The given program.
EAPI Embryo_Program* embryo_program_load (char * file)
Creates a new Embryo program based on the bytecode data stored in the given file.
Parameters:
file Filename of the given file.
Returns:
A new Embryo program.
References embryo_program_new(), and embryo_swap_32().
EAPI Embryo_Program* embryo_program_new (void * data, int size)
Creates a new Embryo program, with bytecode data that can be freed.
Parameters:
data Pointer to the bytecode of the program.
size Number of bytes of bytecode.
Returns:
A new Embryo program.
Referenced by embryo_program_load().
Copyright © Enlightenment.org
Embryo Documentation Generated: Mon May 19 09:42:59 2008