Embryo: Function Parameter Functions
Home
News
About
Download
Main Page Modules API Reference Related Pages
Support
Contribute
Contact
Tracker
Function Parameter Functions
Functions that set parameters for the next function that is called.
Functions
EAPI int embryo_parameter_cell_push (Embryo_Program *ep, Embryo_Cell cell)
Pushes an Embryo_Cell onto the function stack to use as a parameter for the next function that is called in the given program.
EAPI int embryo_parameter_string_push (Embryo_Program *ep, const char *str)
Pushes a string onto the function stack to use as a parameter for the next function that is called in the given program.
EAPI int embryo_parameter_cell_array_push (Embryo_Program *ep, Embryo_Cell *cells, int num)
Pushes an array of Embryo_Cells onto the function stack to be used as parameters for the next function that is called in the given program.
Detailed Description
Functions that set parameters for the next function that is called.
Function Documentation
EAPI int embryo_parameter_cell_array_push (Embryo_Program * ep, Embryo_Cell * cells, int num)
Pushes an array of Embryo_Cells onto the function stack to be used as parameters for the next function that is called in the given program.
Parameters:
ep The given program.
cells The array of Embryo_Cells.
num The number of cells in cells.
Returns:
1 if successful. 0 otherwise.
References embryo_parameter_cell_push().
EAPI int embryo_parameter_cell_push (Embryo_Program * ep, Embryo_Cell cell)
Pushes an Embryo_Cell onto the function stack to use as a parameter for the next function that is called in the given program.
Parameters:
ep The given program.
cell The Embryo_Cell to push onto the stack.
Returns:
1 if successful. 0 otherwise.
Referenced by embryo_parameter_cell_array_push().
EAPI int embryo_parameter_string_push (Embryo_Program * ep, const char * str)
Pushes a string onto the function stack to use as a parameter for the next function that is called in the given program.
Parameters:
ep The given program.
str The string to push onto the stack.
Returns:
1 if successful. 0 otherwise.
References embryo_parameter_string_push().
Referenced by embryo_parameter_string_push().
Copyright © Enlightenment.org
Embryo Documentation Generated: Thu Sep 25 12:30:22 2008